[package]
name = "tabula"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"
cqrs-es = "0.4.8"
ledger-parser = "5.1.1"
serde = { version = "1.0", features = ["derive"]}
tokio = { version = "1.27.0", features = ["full"] }
